const api = `/api`;
const path = `./backend`;

const router = [
    { path: `${api}`, module: require(`${path}/auths`) },
    { path: `${api}/dashboard`, module: require(`${path}/dashboard`) },
    { path: `${api}/users`, module: require(`${path}/users`) },
    { path: `${api}/about-details`, module: require(`${path}/about_details`) },
    { path: `${api}/menus`, module: require(`${path}/menus`) },
    { path: `${api}/permissions`, module: require(`${path}/permissions`) },
    { path: `${api}/roles`, module: require(`${path}/roles`) },
    { path: `${api}/brands`, module: require(`${path}/brands`) },
    { path: `${api}/banners`, module: require(`${path}/banners`) },
    { path: `${api}/categories`, module: require(`${path}/categories`) },
    { path: `${api}/sub-categories`, module: require(`${path}/sub_categories`) },
    { path: `${api}/discounts`, module: require(`${path}/discounts`) },
    { path: `${api}/colors`, module: require(`${path}/colors`) },
    { path: `${api}/tags`, module: require(`${path}/tags`) },
    { path: `${api}/products`, module: require(`${path}/products`) },
    { path: `${api}/social-details`, module: require(`${path}/social_details`) },
    { path: `${api}/terms-and-conditions`, module: require(`${path}/terms_and_conditions`) },
    { path: `${api}/faq`, module: require(`${path}/faqs`) },
    { path: `${api}/support-details`, module: require(`${path}/support_details`) },
    { path: `${api}/about-us`, module: require(`${path}/about_us`) },
    { path: `${api}/services`, module: require(`${path}/services`) },
    { path: `${api}/news-letter`, module: require(`${path}/news_letters`) },
    { path: `${api}/return-policies`, module: require(`${path}/return_policies`) },
    { path: `${api}/messages`, module: require(`${path}/messages`) },
    { path: `${api}/like-lists`, module: require(`${path}/like_lists`) },
    { path: `${api}/wish-lists`, module: require(`${path}/wish_lists`) },
    { path: `${api}/carts`, module: require(`${path}/carts`) },
    { path: `${api}/orders`, module: require(`${path}/orders`) },
    { path: `${api}/units`, module: require(`${path}/units`) },
    { path: `${api}/warranties`, module: require(`${path}/warranties`) },
    { path: `${api}/coupons`, module: require(`${path}/coupons`) },
    { path: `${api}/warehouses`, module: require(`${path}/warehouses`) },
    { path: `${api}/stores`, module: require(`${path}/stores`) },
    { path: `${api}/errors`, module: require(`${path}/errors`) },
];

module.exports = router;