module.exports = [
    // const router = [
    { path: '/api', module: require('../auths') },
    { path: '/api/dashboard', module: require('../dashboard') },
    { path: '/api/users', module: require('../users') },
    { path: '/api/about-details', module: require('../about_details') },
    { path: '/api/menus', module: require('../menus') },
    { path: '/api/permissions', module: require('../permissions') },
    { path: '/api/roles', module: require('../roles') },
    { path: '/api/brands', module: require('../brands') },
    { path: '/api/banners', module: require('../banners') },
    { path: '/api/categories', module: require('../categories') },
    { path: '/api/sub-categories', module: require('../sub_categories') },
    { path: '/api/discounts', module: require('../discounts') },
    { path: '/api/colors', module: require('../colors') },
    { path: '/api/tags', module: require('../tags') },
    { path: '/api/products', module: require('../products') },
    { path: '/api/social-details', module: require('../social_details') },
    { path: '/api/terms-and-conditions', module: require('../terms_and_conditions') },
    { path: '/api/faq', module: require('../faqs') },
    { path: '/api/support-details', module: require('../support_details') },
    { path: '/api/about-us', module: require('../about_us') },
    { path: '/api/services', module: require('../services') },
    { path: '/api/news-letter', module: require('../news_letters') },
    { path: '/api/return-policies', module: require('../return_policies') },
    { path: '/api/messages', module: require('../messages') },
    { path: '/api/like-lists', module: require('../like_lists') },
    { path: '/api/wish-lists', module: require('../wish_lists') },
    { path: '/api/carts', module: require('../carts') },
    { path: '/api/orders', module: require('../orders') },
    { path: '/api/units', module: require('../units') },
    { path: '/api/warranties', module: require('../warranties') },
    { path: '/api/coupons', module: require('../coupons') },
    { path: '/api/warehouses', module: require('../warehouses') },
    { path: '/api/stores', module: require('../stores') },
];

// module.exports = router;