const routes = [
    { path: '/api', module: require('../auths') },
    { path: '/api/faq', module: require('../faqs') },
    { path: '/api/tags', module: require('../tags') },
    { path: '/api/users', module: require('../users') },
    { path: '/api/roles', module: require('../roles') },
    { path: '/api/menus', module: require('../menus') },
    { path: '/api/colors', module: require('../colors') },
    { path: '/api/brands', module: require('../brands') },
    { path: '/api/banners', module: require('../banners') },
    { path: '/api/messages', module: require('../messages') },
    { path: '/api/products', module: require('../products') },
    { path: '/api/discounts', module: require('../discounts') },
    { path: '/api/dashboard', module: require('../dashboard') },
    { path: '/api/categories', module: require('../categories') },
    { path: '/api/permissions', module: require('../permissions') },
    { path: '/api/news-letter', module: require('../news_letters') },
    { path: '/api/about-details', module: require('../about_details') },
    { path: '/api/sub-categories', module: require('../sub_categories') },
    { path: '/api/social-details', module: require('../social_details') },
    { path: '/api/support-details', module: require('../support_details') },
    { path: '/api/terms-and-conditions', module: require('../terms_and_conditions') },
];

module.exports = routes;